config:
  default: true
  MD004:
    style: asterisk
  MD013: false
  MD026:
    punctuation: '.,;:!'
  MD029:
    style: ordered
  MD033: false
  MD034: false
  MD041: false
  MD051: false
ignores:
  - "{,docs/}{RELEASE,release,CHANGELOG,changelog}.md"
  - tools/autotag/templates/**/*.md
