variables:
- group: common
- template: /.azuredevops/variables-global.yml

parameters:
- name: catch2Version
  type: string
  default: "v3.7.0"

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_DEPENDENCIES_PATH }}/catch2.yml
    parameters:
      catch2Version: ${{ parameters.catch2Version }}
