variables:
- group: common
- template: /.azuredevops/variables-global.yml

parameters:
- name: libdivideVersion
  type: string
  default: master

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm

trigger: none
pr: none

jobs:
  - template: ${{ variables.CI_DEPENDENCIES_PATH }}/libdivide.yml
    parameters:
      libdivideVersion: ${{ parameters.libdivideVersion }}
