parameters:
- name: checkoutRepo
  type: string
  default: 'self'
- name: checkoutRef
  type: string
  default: ''
# set to true if doing full build of ROCm stack
# and dependencies are pulled from same pipeline
- name: aggregatePipeline
  type: boolean
  default: false
# reference:
# https://github.com/ROCm/aomp/blob/aomp-dev/docs/SOURCEINSTALL_PREREQUISITE.md
- name: aptPackages
  type: object
  default:
    - cmake
    - python3-pip
    - ninja-build
    - pkg-config
    - libpci-dev
    - libnuma-dev
    - libffi-dev
    - git
    - libopenmpi-dev
    - gawk
    - mesa-common-dev
    - libtool
    - libdrm-amdgpu1
    - libdrm-dev
    - libdw-dev
    - libgtest-dev
    - libsystemd-dev
    - libssl-dev
    - libstdc++-12-dev
    - ccache
    - libgmp-dev
    - libmpfr-dev
    - texinfo
    - libbison-dev
    - bison
    - flex
    - libbabeltrace-dev
    - libncurses5-dev
    - liblzma-dev
    - python3-setuptools
    - python3-dev
    - libudev-dev
    - parallel
  # Referencing comment snippet.
  #
  # snippet from https://github.com/ROCm/aomp/blob/aomp-dev/bin/build_aomp.sh#L131-L134
  #
  # For ROCM build (AOMP_STANDALONE_BUILD=0) the components roct, rocr,
  # libdevice, project, comgr, rocminfo, hipamd, rocdbgapi, rocgdb,
  # roctracer, rocprofiler, rocm_smi_lib, and amdsmi should be found
  # in ROCM in /opt/rocm.  The ROCM build only needs these components:
- name: rocmDependencies
  type: object
  default:
    - amdsmi
    - clr
    - llvm-project
    - ROCdbgapi
    - ROCgdb
    - rocm-cmake
    - rocm-core
    - rocminfo
    - rocm_smi_lib
    - rocprofiler
    - rocprofiler-register
    - rocprofiler-sdk
    - ROCR-Runtime
    - roctracer

- name: jobMatrix
  type: object
  default:
    testJobs:
      - gfx942:
        target: gfx942
      - gfx90a:
        target: gfx90a

jobs:
- job: aomp
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool: ${{ variables.MEDIUM_BUILD_POOL }}
  workspace:
    clean: all
  steps:
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-other.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
# checkout the repos tied to openmp-extras, plus llvm-project
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: ${{ parameters.checkoutRepo }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: aomp-extras_repo
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: flang_repo
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
    parameters:
      checkoutRepo: llvm-project_repo
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-rocm.yml
    parameters:
      checkoutRef: ${{ parameters.checkoutRef }}
      dependencyList: ${{ parameters.rocmDependencies }}
      aggregatePipeline: ${{ parameters.aggregatePipeline }}
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      componentName: extras
      cmakeBuildDir: '$(Build.SourcesDirectory)/aomp-extras/build'
      installDir: '$(Build.BinariesDirectory)/llvm'
      extraBuildFlags: >-
        -DLLVM_DIR=$(Agent.BuildDirectory)/rocm/llvm
        -DCMAKE_BUILD_TYPE=Release
        -DAOMP_STANDALONE_BUILD=0
        -DAOMP_VERSION_STRING=9.99.99
        -GNinja
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      componentName: openmp
      cmakeBuildDir: '$(Build.SourcesDirectory)/llvm-project/openmp/build'
      installDir: '$(Build.BinariesDirectory)/llvm'
      extraBuildFlags: >-
        -DCMAKE_PREFIX_PATH="$(Agent.BuildDirectory)/rocm;$(Build.BinariesDirectory)"
        -DCMAKE_BUILD_TYPE=Release
        -DOPENMP_TEST_CXX_COMPILER=$(Agent.BuildDirectory)/rocm/llvm/bin/clang++
        -DOPENMP_TEST_C_COMPILER=$(Agent.BuildDirectory)/rocm/llvm/bin/clang
        -DCMAKE_CXX_COMPILER=$(Agent.BuildDirectory)/rocm/llvm/bin/clang++
        -DCMAKE_C_COMPILER=$(Agent.BuildDirectory)/rocm/llvm/bin/clang
        -DOPENMP_ENABLE_LIBOMPTARGET=1
        -DLIBOMP_COPY_EXPORTS=OFF
        -DLIBOMP_OMPT_SUPPORT=ON
        -DLIBOMP_OMPD_SUPPORT=ON
        -DCMAKE_SKIP_INSTALL_RPATH=TRUE
        -DLLVM_MAIN_INCLUDE_DIR=$(Build.SourcesDirectory)/llvm-project/llvm/include
        -DLIBOMP_FORTRAN_MODULES_COMPILER=$(Agent.BuildDirectory)/rocm/llvm/bin/flang
        -DLIBOMP_MODULES_INSTALL_PATH=$(Build.BinariesDirectory)/llvm/include/flang/
        -GNinja
  - task: Bash@3
    displayName: 'ROCm symbolic link'
    inputs:
      targetType: inline
      script: sudo ln -s $(Agent.BuildDirectory)/rocm /opt/rocm
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/build-cmake.yml
    parameters:
      componentName: offload
      cmakeBuildDir: '$(Build.SourcesDirectory)/llvm-project/offload/build'
      installDir: '$(Build.BinariesDirectory)/llvm'
      extraBuildFlags: >-
        -DCMAKE_PREFIX_PATH="$(Agent.BuildDirectory)/rocm;$(Build.BinariesDirectory)"
        -DCMAKE_BUILD_TYPE=Release
        -DOPENMP_TEST_CXX_COMPILER=$(Agent.BuildDirectory)/rocm/llvm/bin/clang++
        -DOPENMP_TEST_C_COMPILER=$(Agent.BuildDirectory)/rocm/llvm/bin/clang
        -DCMAKE_CXX_COMPILER=$(Agent.BuildDirectory)/rocm/llvm/bin/clang++
        -DCMAKE_C_COMPILER=$(Agent.BuildDirectory)/rocm/llvm/bin/clang
        -DCMAKE_SKIP_INSTALL_RPATH=TRUE
        -DLLVM_MAIN_INCLUDE_DIR=$(Build.SourcesDirectory)/llvm-project/llvm/include
        -DLIBOMPTARGET_LLVM_INCLUDE_DIRS=$(Build.SourcesDirectory)/llvm-project/llvm/include
        -DCMAKE_EXE_LINKER_FLAGS="-L$(Agent.BuildDirectory)/rocm/llvm/lib"
        -DCMAKE_SHARED_LINKER_FLAGS="-L$(Agent.BuildDirectory)/rocm/llvm/lib"
        -GNinja
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/manifest.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-upload.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/artifact-links.yml
  - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/docker-container.yml
    parameters:
      aptPackages: ${{ parameters.aptPackages }}

- ${{ each job in parameters.jobMatrix.testJobs }}:
  - job: aomp_test_${{ job.target }}
    dependsOn: aomp
    condition:
      and(succeeded(),
        eq(variables['ENABLE_${{ upper(job.target) }}_TESTS'], 'true'),
        not(containsValue(split(variables['DISABLED_${{ upper(job.target) }}_TESTS'], ','), variables['Build.DefinitionName'])),
        eq(${{ parameters.aggregatePipeline }}, 'false')
      )
    variables:
    - group: common
    - template: /.azuredevops/variables-global.yml
    pool: ${{ job.target }}_test_pool
    workspace:
      clean: all
    steps:
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-other.yml
      parameters:
        aptPackages: ${{ parameters.aptPackages }}
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/preamble.yml
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/local-artifact-download.yml
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/dependencies-rocm.yml
      parameters:
        checkoutRef: ${{ parameters.checkoutRef }}
        dependencyList: ${{ parameters.rocmDependencies }}
    - task: Bash@3
      displayName: ROCm symbolic link
      inputs:
        targetType: inline
        script: sudo ln -s $(Agent.BuildDirectory)/rocm /opt/rocm
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
      parameters:
        checkoutRepo: ${{ parameters.checkoutRepo }}
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/checkout.yml
      parameters:
        checkoutRepo: aomp-extras_repo
  # these copy steps are from the aomp prototype script for test prep
    - task: CopyFiles@2
      displayName: 'Copy AOMP contents'
      inputs:
        CleanTargetFolder: false
        SourceFolder: $(Build.SourcesDirectory)/aomp
        Contents: |
          **
          !**/.git/**
          !**/.github/**
          !**/.gitignore
        TargetFolder: $(Agent.BuildDirectory)/rocm/share/openmp-extras/tests
        retryCount: 3
    - task: CopyFiles@2
      displayName: 'Copy FileCheck'
      inputs:
        CleanTargetFolder: false
        SourceFolder: $(Agent.BuildDirectory)/rocm/llvm/bin
        Contents: FileCheck
        TargetFolder: $(Agent.BuildDirectory)/rocm/share/openmp-extras/tests/bin
        retryCount: 3
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/gpu-diagnostics.yml
    - task: Bash@3
      displayName: Test AOMP
      continueOnError: true
      inputs:
        targetType: inline
        script: ./run_rocm_test.sh
        workingDirectory: $(Build.SourcesDirectory)/aomp/bin
      env:
        AOMP: $(Agent.BuildDirectory)/rocm/llvm
        AOMP_REPOS_TEST: $(Build.SourcesDirectory)/aomp-test
        AOMP_TEST_DIR: $(Build.SourcesDirectory)/aomp-test
        SKIP_TEST_PACKAGE: 1
        MAINLINE_BUILD: 1
        SUITE_LIST: smoke
    - template: ${{ variables.CI_TEMPLATE_PATH }}/steps/docker-container.yml
      parameters:
        aptPackages: ${{ parameters.aptPackages }}
        environment: test
        gpuTarget: ${{ job.target }}
        optSymLink: true
